name = "FD&C Blue 1"
led = 630 
units = "mg/L" 
fit_type = "polynomial"
fit_order = 1
values = [ 
    [0.0, 1.5857, 3.1714, 4.7571, 6.3428, 7.9285],
    [0.0,   0.16,   0.36,   0.51,   0.64,   0.81]
    ]
